package com.example.qurannexus.core.database


import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import com.example.qurannexus.core.database.converters.ListConverter
import com.example.qurannexus.core.database.entities.*
import com.example.qurannexus.features.analysis.data.WordRootDao // Updated DAO name

@Database(
    entities = [
        RootEntity::class,
        ArabicFormEntity::class,
        ArabicFormTransliterationEntity::class,
        ArabicFormTranslationEntity::class,
        RootContributingMorphFormEntity::class,
        RootSurahDistributionEntity::class,
        RootJuzDistributionEntity::class,
        RootPageDistributionEntity::class,
        RootWordOccurrenceEntity::class
    ],
    version = 1, // Start with version 1 for the new schema
    exportSchema = false // Set to true for production, add schema location in build.gradle
)
@TypeConverters(ListConverter::class)
abstract class QuranNexusDatabase : RoomDatabase() {

    abstract fun wordRootDao(): WordRootDao // Updated DAO name

    companion object {
        @Volatile
        private var INSTANCE: QuranNexusDatabase? = null
        // Ensure this matches the .db file generated by your Python script (v5)
        private const val DATABASE_NAME = "quran_root_analysis_v5.db"

        fun getDatabase(context: Context): QuranNexusDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    QuranNexusDatabase::class.java,
                    DATABASE_NAME
                )
                    .createFromAsset("database/$DATABASE_NAME")
                    // IMPORTANT: If you change the schema (version++), you'll need a migration strategy
                    // or use fallbackToDestructiveMigration() during development (data will be lost on upgrade).
                    .fallbackToDestructiveMigration() // For development: if schema changes, recreates DB
                    .build()
                INSTANCE = instance
                instance
            }
        }
    }
}